# Generated by Django 2.0.5 on 2019-08-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='optional',
            field=models.TextField(blank=True),
        ),
    ]
