# Generated by Django 2.0.5 on 2019-08-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
