# Generated by Django 2.0.5 on 2019-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buy_paidcontent',
            field=models.BooleanField(default=False, verbose_name='Оплатил контент?'),
        ),
    ]
